name: BooBoo Quality Assurance
on: [push,pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3','7.4','8.0']
        phpunit-versions: ['latest']
    steps:
      - name: Check Out Default Actions
        uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.12.0
        with:
            php-version: ${{ matrix.php-versions }}
            coverage: xdebug
            tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Run Unit Tests
        run: phpunit

